stages:
 - test
 - quality

include:
  - project: 'paydock/platform/gitlab-templates'
    ref: feature/FND-579/clean-up-pipeline
    file: '/security/gitlab-security-scans.yaml'
  - project: 'paydock/platform/gitlab-templates'
    ref: feature/FND-579/clean-up-pipeline
    file: '/code_quality.yml'
