image: 412245956714.dkr.ecr.ap-southeast-2.amazonaws.com/docker-hub/library/amazoncorretto:21-alpine

stages:
 - test
 - publish
 - quality

include:
  - project: 'paydock/platform/gitlab-templates'
    file: '/deploy/version.yml'
  - project: 'paydock/platform/gitlab-templates'
    file: '/security/gitlab-security-scans.yaml'
  - project: 'paydock/platform/gitlab-templates'
    file: '/code_quality.yml'

prepare_power_board_version:
  stage: publish
  only:
    - power_board
  needs:
    - job: create_version
      artifacts: true
  script:
    - VERSION=$(cat version)
    - MAJOR_MINOR=$(cat power-board.php | grep "POWER_BOARD_PLUGIN_VERSION'," | sed -e "s/^.*\([0-9].[0-9].[0-9]\).*$/\1/")
    - echo "ARTIFACT_NAME=woo_powerboard-$MAJOR_MINOR-$VERSION" > VERSION.TXT
  artifacts:
    reports:
      dotenv: VERSION.TXT

publish_power_board:
  stage: publish
  only:
    - power_board
  needs:
    - prepare_power_board_version
  script:
    - echo $ARTIFACT_NAME
  artifacts:
    name: $ARTIFACT_NAME
    paths:
      - ./*
    exclude:
      - .git/*
      - .gitignore
      - .github/*
      - .gitlab-ci.yml
      - .codeclimate.yml
      - .idea/*
      - screenshot-*.png
      - phpstan.neon
      - phpcs2codeclimate.py
      - phpcs.xml
      - eslint.config.mjs
      - Dockerfile.powerboard
      - Dockerfile.paydock

prepare_paydock_version:
  stage: publish
  only:
    - main
  needs:
    - job: create_version
      artifacts: true
  script:
    - VERSION=$(cat version)
    - MAJOR_MINOR=$(cat paydock.php | grep "PAYDOCK_PLUGIN_VERSION'," | sed -e "s/^.*\([0-9].[0-9].[0-9]\).*$/\1/")
    - echo "ARTIFACT_NAME=woo_paydock-$MAJOR_MINOR-$VERSION" > VERSION.TXT
  artifacts:
    reports:
      dotenv: VERSION.TXT

publish_paydock:
  stage: publish
  only:
    - main
  needs:
    - prepare_paydock_version
  script:
    - echo $ARTIFACT_NAME
  artifacts:
    name: $ARTIFACT_NAME
    paths:
      - ./*
    exclude:
      - .git/*
      - .gitignore
      - .github/*
      - .gitlab-ci.yml
      - .codeclimate.yml
      - .idea/*
      - screenshot-*.png
      - phpstan.neon
      - phpcs2codeclimate.py
      - phpcs.xml
      - eslint.config.mjs
      - Dockerfile.powerboard
      - Dockerfile.paydock

run_phpcs:
  image: composer:lts
  stage: quality
  script:
    - composer install
    - ./vendor/bin/phpcs --report=json . > phpcs-report.json || true
    - ls phpcs-report.json
  artifacts:
    name: phpcs-report.json
    paths:
      - phpcs-report.json

phpcs_report:
  image: python:3.9-slim
  stage: quality
  needs:
    - job: run_phpcs
      artifacts: true
  script:
    - python phpcs2codeclimate.py
  artifacts:
    reports:
      codequality:
        - code_climate_phpcs_report.json
