name: Build and create Payments Plugin for WooCommerce Zip files

on:
  push:
    branches:
      - plugin-single-code-base

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Prepare PowerBoard build file
        run: |
          chmod +x ./build/build-powerboard.prod.sh
          ./build/build-powerboard.prod.sh

      - name: Create PowerBoard build file
        run:
          zip -r power-board.zip . -x 'build/*' '.git/*' '.github/*' '.gitignore' '.gitlab-ci.yml' 'node.sh' '*.zip'

      - name: Prepare Paydock build file
        run: |
          chmod +x ./build/build-paydock.prod.sh
          ./build/build-paydock.prod.sh

      - name: Create Paydock build file
        run:
          zip -r paydock.zip . -x 'build/*' '.git/*' '.github/*' '.gitignore' '.gitlab-ci.yml' 'node.sh' '*.zip'

      - name: Upload PowerBoard artifact
        uses: actions/upload-artifact@v4
        with:
          name: power-board
          path: power-board.zip

      - name: Upload Paydock artifact
        uses: actions/upload-artifact@v4
        with:
          name: paydock
          path: paydock.zip

      - name: List ZIP contents
        run:
          unzip -l power-board.zip

#      - name: Upload to Google Drive
#        uses: google-github-actions/upload-cloud-storage@v0.8.0
#        with:
#          path: paydock.zip
#          destination: 1mwR5ruoRrGF4cYa1TMlSyy-FYm-m2ZmP/paydock.zip
#          credentials: ${{ secrets.GDRIVE_SA_KEY }}
