name: Build and upload Paydock for WooCommerce plugin

on:
  push:
    branches:
      - power_board
  pull_request:
    branches:
      - power_board
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare files for upload
        run: |
          mkdir artifacts
          rsync -av --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='*.zip' ./ artifacts/

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: power_board
          path: artifacts/

#      - name: Zip the plugin
#        run: zip -r power_board.zip artifacts/

#      - name: Upload to Google Drive
#        uses: google-github-actions/upload-cloud-storage@v0.8.0
#        with:
#          path: power_board.zip
#          destination: 1mwR5ruoRrGF4cYa1TMlSyy-FYm-m2ZmP/power_board.zip
#          credentials: ${{ secrets.GDRIVE_SA_KEY }}
