name: Build and create Payments Plugin for WooCommerce Zip files

on:
  push:
    branches:
      - plugin-single-code-base

jobs:
  power_board:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Prepare PowerBoard build file
        run: |
          chmod +x ./build/build-powerboard.prod.sh
          ./build/build-powerboard.prod.sh
          npm install
          npm run build

      - name: Create PowerBoard build file
        run:
          rsync -av --exclude='build/*' --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='.gitlab-ci.yml' --exclude='node.sh' --exclude='*.zip' --exclude='node_modules/*' ./ artifacts/

      - name: Upload PowerBoard artifact
        uses: actions/upload-artifact@v4
        with:
          name: power-board
          path: artifacts/

  paydock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Prepare Paydock build file
        run: |
          chmod +x ./build/build-paydock.prod.sh
          ./build/build-paydock.prod.sh
          npm install
          npm run build

      - name: Create Paydock build file
        run:
          rsync -av --exclude='build/*' --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='.gitlab-ci.yml' --exclude='node.sh' --exclude='*.zip' --exclude='node_modules/*' ./ artifacts/

      - name: Upload Paydock artifact
        uses: actions/upload-artifact@v4
        with:
          name: paydock
          path: artifacts/
